### ISSUE TITLE
Access etcd wach api without akka streams[Feature Request]

### ISSUE THREAD

**Issue by erangaeb** [mingchuno/etcd4s#24]
Hi,

Are there any possibility to access watch API without using akka-streams. Could you please provide some example?

Would that be possible to have `KVService`, `setKey()` function with the lease parameter?

**Comment by mingchuno** [comment]
You do ask me via email but I will post my reply here so that everyone can see it.

> 
> After revising the code. I did not expose all the underlying grpc APIs to the service layer (https://github.com/mingchuno/etcd4s/tree/master/etcd4s-core/src/main/scala/org/etcd4s/rpc)
> The underlying PutRequest does have a much richer option to choose from. It is the same for the Watch API. I do wrap the Watch API with akka-stream for easier to use in the first place. 
> If I did not wrap the Watch API with akka-stream, the signature should be `def watch(responseObserver: io.grpc.stub.StreamObserver[WatchResponse]): io.grpc.stub.StreamObserver[WatchRequest]`
> 
> So for your question, I can redesign the APIs and expose more of the underlying services to lib user...What do you think?
